/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    shoes_r_mesh: THREE.SkinnedMesh;
    shoes_r_mesh_1: THREE.SkinnedMesh;
    shoes_l_mesh: THREE.SkinnedMesh;
    shoes_l_mesh_1: THREE.SkinnedMesh;
    hair_mesh: THREE.SkinnedMesh;
    eyelash_L_mesh: THREE.SkinnedMesh;
    eyelash_R_mesh: THREE.SkinnedMesh;
    tooth_mesh: THREE.SkinnedMesh;
    eye_L_mesh: THREE.SkinnedMesh;
    eye_R_mesh: THREE.SkinnedMesh;
    body_mesh: THREE.SkinnedMesh;
    body_mesh_1: THREE.SkinnedMesh;
    body_mesh_2: THREE.SkinnedMesh;
    body_mesh_3: THREE.SkinnedMesh;
    Cloth_mesh: THREE.Mesh;
    Cloth_mesh_1: THREE.Mesh;
    Cloth_mesh_2: THREE.Mesh;
    Cloth_mesh_3: THREE.Mesh;
    Cloth_mesh_4: THREE.Mesh;
    Cloth_mesh_5: THREE.Mesh;
    Cloth_mesh_6: THREE.Mesh;
    Cloth_mesh_7: THREE.Mesh;
    Cloth_mesh_8: THREE.Mesh;
    Cloth_mesh_9: THREE.Mesh;
    Joint: THREE.Bone;
    eyelash_L: THREE.Bone;
    eyelash_R: THREE.Bone;
    tooth: THREE.Bone;
    eye_L: THREE.Bone;
    eye_R: THREE.Bone;
    body: THREE.Bone;
  };
  materials: {
    M_Thomas_Sneaker_A_03_Male_Sneaker_02_opencollada_Female_Sneaker_02_opencollada_man_sports_shoes_shoesFBXASC045fx2SG1SG1SG1SG1S1: THREE.MeshPhysicalMaterial;
    M_Thomas_Sneaker_A_03_Male_Sneaker_02_opencollada_Female_Sneaker_02_opencollada_dummy1FBXASC045fx2SG1SG1SG1SG1SG1SG1SG1: THREE.MeshPhysicalMaterial;
    defaultMat1: THREE.MeshPhysicalMaterial;
    eyelash: THREE.MeshPhysicalMaterial;
    toothSG1: THREE.MeshPhysicalMaterial;
    eye: THREE.MeshPhysicalMaterial;
    face: THREE.MeshPhysicalMaterial;
    body2: THREE.MeshPhysicalMaterial;
    arm: THREE.MeshPhysicalMaterial;
    leg: THREE.MeshPhysicalMaterial;
    Wool_Cashmere_FRONT_2205182: THREE.MeshPhysicalMaterial;
    Wool_Cashmere_FRONT_2205182: THREE.MeshPhysicalMaterial;
    Cotton_Stretch_Velvet_FRONT_2205193: THREE.MeshPhysicalMaterial;
    Cotton_Stretch_Velvet_FRONT_2205193: THREE.MeshPhysicalMaterial;
    Cotton_Stretch_Velvet_FRONT_2205193: THREE.MeshPhysicalMaterial;
    Cotton_Stretch_Velvet_FRONT_2205193: THREE.MeshPhysicalMaterial;
    Wool_Cashmere_FRONT_2205182: THREE.MeshPhysicalMaterial;
    PT_FABRIC_FRONT_2212751: THREE.MeshPhysicalMaterial;
    Wool_Cashmere_FRONT_2205182: THREE.MeshPhysicalMaterial;
    PT_FABRIC_FRONT_2212767: THREE.MeshPhysicalMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Final Summer.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Joint} />
      <primitive object={nodes.eyelash_L} />
      <primitive object={nodes.eyelash_R} />
      <primitive object={nodes.tooth} />
      <primitive object={nodes.eye_L} />
      <primitive object={nodes.eye_R} />
      <primitive object={nodes.body} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh.geometry}
        material={materials.Wool_Cashmere_FRONT_2205182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials.Wool_Cashmere_FRONT_2205182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials.Cotton_Stretch_Velvet_FRONT_2205193}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials.Cotton_Stretch_Velvet_FRONT_2205193}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials.Cotton_Stretch_Velvet_FRONT_2205193}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials.Cotton_Stretch_Velvet_FRONT_2205193}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_6.geometry}
        material={materials.Wool_Cashmere_FRONT_2205182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_7.geometry}
        material={materials.PT_FABRIC_FRONT_2212751}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_8.geometry}
        material={materials.Wool_Cashmere_FRONT_2205182}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cloth_mesh_9.geometry}
        material={materials.PT_FABRIC_FRONT_2212767}
      />
    </group>
  );
}

useGLTF.preload("/Final Summer.gltf");
